/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { useState } from "react";
import { useQuery } from "react-query";
import { pixabayService, Title } from "shared";

import { styled } from "linaria/react";

// Write your styles in `styled` tag
// const Title = styled.h1`
//   font-family: ;
// `;

const Container = styled.main`
  font-size: 14px;
  color: ${(props) => props.color};
  border: 1px solid red;
  &:hover {
    border-color: blue;
  }
`;

export default function Home() {
  const [searchTerm, setSearchTerm] = useState<string>("");

  const { data: photos, isLoading } = useQuery(
    ["get-photos", searchTerm],
    pixabayService.getPhotos,
    {}
  );

  console.log("PHOTOS", photos);

  return (
    <div>
      <Head>
        <title>PIXABAY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Title>IMAGES</Title>
        {photos?.hits.map((photo) => (
          <img key={photo?.id} src={photo?.previewURL} alt={photo?.user} />
        ))}
      </Container>
    </div>
  );
}
